import { StyleSheet } from 'react-native';

export const homeScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000000',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: 60,
    paddingBottom: 16,
    width: '100%',
    backgroundColor: '#000000',
  },
  profilePicContainer: {
    padding: 2,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#2C2C2E',
    marginRight: 12,
  },
  headerAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
  },
  title: {
    fontSize: 28,
    fontWeight: '600',
    marginBottom: 0,
    color: '#ffffff',
    textAlign: 'left',
    letterSpacing: -0.5,
  },
  description: {
    fontSize: 15,
    color: '#8E8E93',
    textAlign: 'center',
    marginBottom: 32,
    lineHeight: 20,
    fontWeight: '400',
    maxWidth: 280,
  },
  signInContainer: {
    alignItems: 'center',
    backgroundColor: '#1C1C1E',
    borderRadius: 16,
    padding: 32,
    maxWidth: 320,
    width: '100%',
    borderWidth: 1,
    borderColor: '#2C2C2E',
  },
  userContainer: {
    alignItems: 'center',
    backgroundColor: '#1C1C1E',
    borderRadius: 16,
    padding: 24,
    marginBottom: 16,
    maxWidth: 320,
    width: '100%',
    borderWidth: 1,
    borderColor: '#2C2C2E',
  },
  avatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    marginBottom: 16,
    borderWidth: 2,
    borderColor: '#2C2C2E',
  },
  userName: {
    fontSize: 20,
    fontWeight: '600',
    color: '#ffffff',
    marginBottom: 4,
    textAlign: 'center',
    letterSpacing: -0.3,
  },
  userEmail: {
    fontSize: 14,
    color: '#8E8E93',
    marginBottom: 4,
    textAlign: 'center',
    fontWeight: '400',
  },
  userId: {
    fontSize: 12,
    color: '#636366',
    marginBottom: 20,
    textAlign: 'center',
    fontWeight: '400',
  },
  signInButton: {
    backgroundColor: '#007AFF',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 200,
    height: 44,
  },
  disabledButton: {
    backgroundColor: '#2C2C2E',
    opacity: 0.6,
  },
  signOutButton: {
    backgroundColor: '#FF3B30',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 10,
    marginTop: 16,
    height: 40,
  },
  tokenButton: {
    backgroundColor: '#34C759',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 10,
    marginBottom: 16,
    height: 40,
  },
  tokenContainer: {
    marginTop: 20,
    padding: 16,
    backgroundColor: '#1C1C1E',
    borderRadius: 12,
    width: '100%',
    borderWidth: 1,
    borderColor: '#2C2C2E',
  },
  tokenTitle: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 12,
    color: '#ffffff',
  },
  tokenViewButton: {
    backgroundColor: '#007AFF',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    marginBottom: 12,
    alignSelf: 'flex-start',
    height: 32,
  },
  tokenButtonText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '500',
  },
  tokenText: {
    fontSize: 11,
    fontFamily: 'monospace',
    backgroundColor: '#2C2C2E',
    padding: 12,
    borderRadius: 8,
    marginBottom: 12,
    color: '#8E8E93',
    lineHeight: 16,
  },
  tokenNote: {
    fontSize: 11,
    color: '#636366',
    fontStyle: 'italic',
    textAlign: 'center',
    marginTop: 8,
    fontWeight: '400',
  },
  buttonText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '500',
  },
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: '#1C1C1E',
    borderRadius: 12,
    marginHorizontal: 24,
    marginBottom: 20,
    padding: 4,
    borderWidth: 1,
    borderColor: '#2C2C2E',
  },
  tabButton: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  activeTabButton: {
    backgroundColor: '#007AFF',
  },
  tabButtonText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#8E8E93',
  },
  activeTabButtonText: {
    color: '#ffffff',
  },
  contentContainer: {
    flex: 1,
    width: '100%',
  },
  loadingContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1C1C1E',
    borderRadius: 16,
    padding: 32,
    maxWidth: 320,
    width: '100%',
    borderWidth: 1,
    borderColor: '#2C2C2E',
  },
  loadingText: {
    fontSize: 16,
    color: '#8E8E93',
    textAlign: 'center',
    fontWeight: '400',
  },
});